/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jconga;

import baraja.Carta;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author luiss
 */
public class ArmarJuego extends javax.swing.JDialog {

    private ArrayList<Carta> cartas = new ArrayList<>();
    // Botones para mostrar las cartas del juego
    private ArrayList<PanelCarta> botonesJuego = new ArrayList<>();
    //Objeto auxiliar para la carta seleccionada
    PanelCarta cartaSel;
    
    
    /** Creates new form ArmarJuego: NO USAR */
    public ArmarJuego(java.awt.Frame parent, boolean modal ) {
        super(parent, modal);
        initComponents();
        
    }
    
    /**
     * Inicializa la ventana para organizar el 'juego' del jugador
     * @param parent Ventana base del juego. Requerida para usar la ventana como modal
     * @param modal Debe ser true
     * @param cartas ArrayList con las cartas que forman el juego.
     */
    public ArmarJuego(java.awt.Frame parent, boolean modal, ArrayList<Carta> cartas){
        super(parent, modal);
        initComponents();
        
        //Parámetros de posicionamiento
        int posX = 10;
        int posY = 10;
        
        //Establecemos el tamaño de la ventana según la cantidad de cartas
        /*this.setSize(
                (30+(110*cartas.size())),
                this.getSize().height);
        */
        //Creación y ubicación de las cartas en la ventana
        this.cartas = cartas;
        AsignarCartas();
        /*for(Carta carta:cartas){
            PanelCarta btn = new PanelCarta();
            
            getContentPane().add(btn);
            Rectangle posicion = new Rectangle(posX,posY,108,164);
            btn.setBounds(posicion);
            
            getContentPane().revalidate();
            validate();

            btn.addMouseListener(
                    new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseClicked(java.awt.event.MouseEvent evt){
                            btn.Seleccionar();
                        }
                    }
            );
            
            botonesJuego.add(btn);
            
            btn.setCarta(carta);
            btn.ActualizarImagen();
            posX = posX + 110;

            
        }*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        btnMovIzq = new javax.swing.JButton();
        btnMovDer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 330));
        setResizable(false);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jconga/imagen/juegoOk.png"))); // NOI18N
        jButton5.setPreferredSize(new java.awt.Dimension(106, 23));

        btnMovIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jconga/imagen/cartaIzquierda.png"))); // NOI18N
        btnMovIzq.setPreferredSize(new java.awt.Dimension(106, 23));

        btnMovDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jconga/imagen/cartaDerecha.png"))); // NOI18N
        btnMovDer.setPreferredSize(new java.awt.Dimension(106, 23));
        btnMovDer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMovDerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnMovIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnMovDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMovIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMovDer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMovDerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovDerMouseClicked
        
        
    }//GEN-LAST:event_btnMovDerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArmarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArmarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArmarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArmarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArmarJuego dialog = new ArmarJuego(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    private void AsignarCartas(){
        //Parámetros de posicionamiento
        int posX = 10;
        int posY = 10;
        
        getContentPane().removeAll();
        
        for (Carta carta : cartas) {
            PanelCarta btn = new PanelCarta();
            
            getContentPane().add(btn);
            Rectangle posicion = new Rectangle(posX,posY,108,164);
            btn.setBounds(posicion);
            
            getContentPane().revalidate();
            validate();

            btn.addMouseListener(
                    new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseClicked(java.awt.event.MouseEvent evt){
                            btn.Seleccionar();
                        }
                    }
            );
            
            botonesJuego.add(btn);
            
            btn.setCarta(carta);
            btn.ActualizarImagen();
            posX = posX + 110;
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMovDer;
    private javax.swing.JButton btnMovIzq;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables

}
