/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jconga;

import baraja.Carta;
//import java.awt.Rectangle;
import java.util.ArrayList;
//import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author luiss
 */
public class PrepararJuego extends javax.swing.JFrame {
    
    private ArrayList<PanelCarta> botonesJuego = new ArrayList<>();
    
    /**
     * Creates new form PrepararJuego
     */
    public PrepararJuego() {
        initComponents();
        //Para pruebas
        //System.out.println("H:"+this.getSize().height + " W:"+this.getSize().width);
    }
    
    public PrepararJuego(ArrayList<Carta> cartas) {
        initComponents();
        
        /**
         * Tamaño base de la ventana: H:277 W:350
         */
        
        this.setSize(
                (10+(110*cartas.size())),
                this.getSize().height);
        
        int posX = 10;
        int posY = 10;
        
        
        
             
        for(Carta carta:cartas){
            PanelCarta btn = new PanelCarta();
            
            getContentPane().add(btn, new AbsoluteConstraints(posX,posY,108,164));
            getContentPane().revalidate();
            validate();
            posX = posX + 110;        

            
            btn.setCarta(carta);
            btn.ActualizarImagen();
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jconga/imagen/juegoOk.png"))); // NOI18N
        jButton5.setPreferredSize(new java.awt.Dimension(106, 23));
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 50));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jconga/imagen/cartaIzquierda.png"))); // NOI18N
        jButton6.setPreferredSize(new java.awt.Dimension(106, 23));
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 50));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jconga/imagen/cartaDerecha.png"))); // NOI18N
        jButton7.setPreferredSize(new java.awt.Dimension(106, 23));
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrepararJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrepararJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrepararJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrepararJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrepararJuego().setVisible(true);
            }
        });
    }
    
    private void CartaSeleccionada(java.awt.event.MouseEvent evt){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
