/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import herramientas.HerramientasVarias;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author luiss
 */
public class Mapa extends javax.swing.JFrame {

    int tamX;
    int tamY;
    int lado;
    Casillero[][] casilleros;
    herramientas.HerramientasVarias varias = new HerramientasVarias();
    
    
    /**
     * Creates new form Mapa
     */
    public Mapa() {
        initComponents();
        //dibujarMapa(limiteX,limiteY,lado);
        this.setSize(400, 100);
        
    }
    
    public Mapa(int tamanio){
        
        
        switch (tamanio) {
            case 0:
                tamX = 15;
                tamY = 9;
                lado = 48;
                break;
            case 1:
                tamX = 25;
                tamY = 15;
                lado = 30;
                break;

            default:
                throw new AssertionError();
        }
        
        int dimX = (tamX*lado)+50;
        int dimY = (tamY*lado)+10;
        
        //System.out.println("dim: "+dimX + "x" + dimY);
        initComponents();
        
        //java.awt.Dimension dim = new Dimension(dimX, dimY);
        dibujarMapa(tamX, tamY, lado);
        setSize(dimY, dimX);
        
        pack();
    }
    
    
    private void dibujarMapa(int limiteX, int limiteY, int lado){
        this.casilleros = new Casillero[tamX][tamY];
        
        JPanel areaJuego = new JPanel();
        areaJuego.setLayout(null);
        areaJuego.setBounds(0, 0, tamX*lado, tamY*lado);
        areaJuego.setBorder(BorderFactory.createLineBorder(Color.yellow));
        
        for (int coordY = 0; coordY < limiteY; coordY++) {
            int y = (coordY==0)?(coordY):(coordY*lado);
            
            for (int coordX = 0; coordX < limiteX; coordX++) {
                int valorCas = varias.alAzarEntre(1, 10);
                
                int x = (coordX==0)?(coordX):(coordX*lado);
                
                Rectangle limites = new Rectangle(x, y, lado, lado);
                
                Casillero cas = new Casillero(limites,valorCas);
                this.casilleros[coordX][coordY] = cas;
                areaJuego.add(cas);

                //this.getContentPane().add(cas);
            }
        }
        this.getContentPane().add(areaJuego);
        pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(743, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
