/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import juegoetsmelo.Partida;

/**
 *
 * @author sebastian
 */
public class Mapa extends javax.swing.JFrame {

    juegoetsmelo.Partida partida;
    Casillero[][] casilleros;
    Dimension tamVentana;
    int limiteX = 20;
    int limiteY = 10;
    /**
     * Creates new form Mapa
     */
    public Mapa() {
        tamVentana = new Dimension((limiteX*51), (limiteY*54));
        initComponents();
        dibujarMapa();
    }

    private void dibujarMapa(){
        
        int x = 0;
        int y = 0;
        
        
        
        casilleros = new Casillero[limiteX][limiteY];
        
        partida = new Partida(limiteX, limiteY);
        
        for(int coordY = 0; coordY < limiteY; coordY++){
            y = 0;
            if (coordY != 0) {
                y = coordY * 50;
            }
            for (int coordX = 0; coordX < limiteX; coordX++){
                x = 0;
                if (coordX != 0) {
                    x = coordX * 50;
                }
                
                int valor = partida.casillero[coordX][coordY];
                Casillero panel = new Casillero(valor, 50, x, y,coordX,coordY);
                this.getContentPane().add(panel);
                
                casilleros[coordX][coordY]=panel;
                
                panel.addMouseListener(
                        
                        new java.awt.event.MouseAdapter() {
                            
                            public void mouseClicked(java.awt.event.MouseEvent ev){
                                
                                moverPersonaje(ev);
                            }
                        }
                );
            }
        }
        
        
        pack();
    }
    
    /**
     * Método para mover al personaje
     * @param evento 
     */
    private void moverPersonaje(java.awt.event.MouseEvent evento){
        System.out.println("probando");
        Component blanco = evento.getComponent();
        Casillero cas = (Casillero) blanco;
        
        int destX = Math.abs(partida.posJ_X - cas.coordX);
        int destY = Math.abs(partida.posJ_Y - cas.coordY);
        
        //if (    (destX==1 & destY==0)
        //     || (destX==0 & destY==1)
        //     || (destX==1 & destY==1)
        //        ) {
        if ((destX+destY)<3){    
            if (cas.valor == 1) {
                casilleros[partida.posJ_X][partida.posJ_Y].cambiarImagen(1);

                partida.posJ_X = cas.coordX;
                partida.posJ_Y = cas.coordY;
                cas.cambiarImagen(0);
            }
            else{
                
            }
        }
        else{
            System.out.println("NO VALIDO");
        }
        
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(this.tamVentana);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
