/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jrobamonton;

/**
 *
 * @author luiss
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_CartaRobar4 = new javax.swing.JButton();
        btn_CartaRobar1 = new javax.swing.JButton();
        btn_CartaRobar2 = new javax.swing.JButton();
        btn_CartaRobar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_CartaRobar4.setText("jButton1");
        btn_CartaRobar4.setPreferredSize(new java.awt.Dimension(106, 140));
        getContentPane().add(btn_CartaRobar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        btn_CartaRobar1.setText("jButton1");
        btn_CartaRobar1.setPreferredSize(new java.awt.Dimension(106, 140));
        getContentPane().add(btn_CartaRobar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        btn_CartaRobar2.setText("jButton1");
        btn_CartaRobar2.setPreferredSize(new java.awt.Dimension(106, 140));
        getContentPane().add(btn_CartaRobar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        btn_CartaRobar3.setText("jButton1");
        btn_CartaRobar3.setPreferredSize(new java.awt.Dimension(106, 140));
        getContentPane().add(btn_CartaRobar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CartaRobar1;
    private javax.swing.JButton btn_CartaRobar2;
    private javax.swing.JButton btn_CartaRobar3;
    private javax.swing.JButton btn_CartaRobar4;
    // End of variables declaration//GEN-END:variables
}
